services:
  api-challenge-visual-software:
    image: ${DOCKER_REGISTRY-}apichallengevisualsoftware
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=banco_voos;Username=postgres;Password=123456
    depends_on:
      - db
    command: >
      bash -c "./wait-for-it.sh db:5432 --timeout=60 -- dotnet ef database update;
               dotnet API-Challenge-Visual-Software.dll"

  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: banco_voos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 10
